<?xml version="1.0"?>
<!DOCTYPE BusinessCard [
<!ELEMENT BusinessCard (name, phone+, email?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (mobile|home|work|fax) #REQUIRED>
<!ELEMENT email (#PCDATA)>
]>
<BusinessCard>
	<name>Joe Marini</name>
	<phone type="mobile">(415) 555-4567</phone>
	<phone type="work">(800) 555-9876</phone>
	<phone type="fax">(510) 555-1234</phone>
	<phone type="home">(425) 555-8989</phone>
	<email>joe@joe.com</email>
</BusinessCard>